faq/urls.py
from django.conf.urls import url
from faq import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index')
]

faq/models.py
from django.db import models


class Topics(models.Model):
    """
    Create a table for sections to list the
    question and answers under.
    """

    topic = models.CharField(max_length=100)

    def __str__(self):
        return self.topic

    class Meta:
        verbose_name = 'topic'
        verbose_name_plural = 'topics'


class Questions(models.Model):
    """
    Create a table to contain all of the
    question and answers to be listed.
    """

    topic = models.ForeignKey(Topics)
    question = models.CharField(max_length=200)
    answer = models.TextField()

    def __str__(self):
        return self.question

    class Meta:
        verbose_name = 'question'
        verbose_name_plural = 'questions'

faq/views.py
from django.shortcuts import render
from django.views import generic
from faq.models import Topics
from faq.models import Questions


class IndexView(generic.ListView):
    template_name = 'faq/index.html'
    context_object_name = 'topic_list'

    def get_queryset(self):
        """Return list of FAQs"""

        return Topics.objects.all()

faq/templates/faq/index.html
{% if topic_list %}
    {% for topic in topic_list %}
        <div>
            <h2>{{ topic.topic }}</h2>

            <ul>
                {% for question in topic.questions_set.all %}
                    <li>{{ question.question }} <br /> {{ question.answer }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endfor %}
{% else %}
    <p>No topics have been created.</p>
{% endif %}